// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFoRPngGR0IVkysOWPXecsvsUTJKIndcI',
    appId: '1:33465475014:web:217cbcc8c05fb62f5c5cc7',
    messagingSenderId: '33465475014',
    projectId: 'habitree-563a5',
    authDomain: 'habitree-563a5.firebaseapp.com',
    storageBucket: 'habitree-563a5.firebasestorage.app',
    measurementId: 'G-NZ791Y9QDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkWoplT5W9ap7bge0uFT0euGDe3y6QPOY',
    appId: '1:33465475014:android:7633745ea8ae6d535c5cc7',
    messagingSenderId: '33465475014',
    projectId: 'habitree-563a5',
    storageBucket: 'habitree-563a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoL5LA5ZGxsk5lRtIawsvDWZZ7UWURuzc',
    appId: '1:33465475014:ios:02bb22cf1bfd9bdb5c5cc7',
    messagingSenderId: '33465475014',
    projectId: 'habitree-563a5',
    storageBucket: 'habitree-563a5.firebasestorage.app',
    iosBundleId: 'com.example.habitree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoL5LA5ZGxsk5lRtIawsvDWZZ7UWURuzc',
    appId: '1:33465475014:ios:02bb22cf1bfd9bdb5c5cc7',
    messagingSenderId: '33465475014',
    projectId: 'habitree-563a5',
    storageBucket: 'habitree-563a5.firebasestorage.app',
    iosBundleId: 'com.example.habitree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFoRPngGR0IVkysOWPXecsvsUTJKIndcI',
    appId: '1:33465475014:web:832dfaf8df6e10d15c5cc7',
    messagingSenderId: '33465475014',
    projectId: 'habitree-563a5',
    authDomain: 'habitree-563a5.firebaseapp.com',
    storageBucket: 'habitree-563a5.firebasestorage.app',
    measurementId: 'G-SVD3FLKPZ7',
  );
}
