name: Deploy Flutter Web to Firebase Hosting (PR)

on:
  pull_request:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter (latest stable)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Build Flutter Web
      - name: Build Web App
        run: flutter build web --release

      # Deploy to Firebase Hosting Preview Channel
      - name: Deploy to Firebase Hosting Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HABITREE_563A5 }}'
          projectId: habitree-563a5
          channelId: pr-${{ github.event.pull_request.number }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
